### ISSUE TITLE
Protocol error 3 on object xdg_surface@11: xdg_surface has never been configured

### ISSUE THREAD

**Issue by andreabolognani** [AlanGriffiths/libinput#4]
Hi,

as I'm struggling to properly calibrate the touchscreen of my xiaomi-daisy device running postmarketOS, I ran into this utility which I thought might be helpful.

After building it from source and running it, however, I'm immediately presented with:

```
Protocol error 3 on object xdg_surface@11: xdg_surface has never been configured
Error: Backend(Protocol(ProtocolError { code: 3, object_id: 11, object_interface: "xdg_surface", message: "xdg_surface has never been configured" }))
```

Based on what I could find elsewhere, this seems to be caused by a wayland protocol violation, in that surfaces are expected to wait for the "configure" event before running "attach". Or something like that, I'm not familiar at all with the protocol :)

Anyway, I thought I'd report this since it seems like it might be a genuine bug in the application.

I'm running it under phosh, in case that makes a difference. The underlying OS is postmarketOS edge, which means that everything should be quite up to date.

**Comment by AlanGriffiths** [comment]
Thanks for the report! It is likely that phosh is relevant as different compositors react differently to protocol errors.

I won't have time to investigate until next week (as I am on vacation), but it is likely that my code is in error.

**Comment by andreabolognani** [comment]
No worries! Enjoy your vacation and let me know if I can provide any additional information to make things easier for you :)

**Comment by andreabolognani** [comment]
Quick update.

I've tried running the app under SXMO (sway version) and the error message is the same.

The app *does* run under plasma-mobile / plasma-desktop (6.0, wayland), but instead of going fullscreen with the origin at 0:0 it starts from the very center of the screen, taking up the bottom-right quarter and being mostly off-screen. In desktop mode, I've been able to use window rules to force it to take up the appropriate position, but the white circle that you're supposed to tap on is not visible. The while circle *does* show up in the preview when alt-tabbing though... Very confusing stuff.

It runs successfully under GNOME (wayland) too, and it seems to be positioned and sized appropriately there, but unfortunately GNOME is extremely glitchy on this hardware so it's not really possible to interact with it.

I'm out of graphical environments that I can try, so I'll just leave it here for now :)

**Comment by Saviq** [comment]
@andreabolognani we primarily work on Mir, so any of the Mir-based compositors should work for you:
- https://snapcraft.io/ubuntu-frame/
- https://github.com/Miriway/Miriway
- https://canonical-mir.readthedocs-hosted.com/stable/getting_and_using_mir/

**Comment by andreabolognani** [comment]
@AlanGriffiths I tried the changes from #5 and the app now runs under phosh. Yay!

Unfortunately I just get a solid-color (slight gradient?) fullscreen window. Interestingly, as was the case with plasma, the spot that I'm supposed to tap *does* show up in the app switcher. See the screenshots below.

I might try to run mir, which thankfully seems to be packaged for Alpine. However, since it's not fully integrated in postmarketOS (it's not offered in the list of UIs one can choose during installation) and considering that I've never used it, that might prove challenging. We'll see :)

<img src="https://github.com/AlanGriffiths/libinput/assets/4943145/b241a193-27e1-419d-bc04-4a6cc94e9e34" width="25%" height="25%"/> <img src="https://github.com/AlanGriffiths/libinput/assets/4943145/6459eca0-ca5e-4693-b9e2-2620998627f3" width="25%" height="25%"/>

**Comment by AlanGriffiths** [comment]
> Unfortunately I just get a solid-color (slight gradient?) fullscreen window. Interestingly, as was the case with plasma, the spot that I'm supposed to tap _does_ show up in the app switcher. See the screenshots below.

I'm guessing that this is because the output is scaled and the calibration app doesn't (currently) accommodate this.

**Comment by andreabolognani** [comment]
> I'm guessing that this is because the output is scaled and the calibration app doesn't (currently) accommodate this.

@AlanGriffiths yes, that was exactly it! After switching to 100% scaling I can see the whole app, including the dot \o/

Is it normal that the dot remains in the same place even after being touched? `wayland-calibrator` moves its own touch target around.

Also, while the app now works, the results I get over different runs are wildly different:

```
99.443  -440.244  159.254  -12.461  -47.270   22.884
42.515    91.751  -46.430    9.507   74.407  -32.038
-2.614  -124.418   52.113  -12.700  -19.056   11.072
```

The numbers I get with `weston-calibrator` seem at least a bit more consistent:

```
0.989313  -0.006107  -14.778618  -0.049727  1.005598   -9.310074
1.033119  -0.006971  -31.545692   0.054943  1.025270  -72.446884
0.969873  -0.012167    8.355133  -0.033024  1.021920  -50.338257
```

I'm really not sure what's up with that.

**Comment by AlanGriffiths** [comment]
> Is it normal that the dot remains in the same place even after being touched? `wayland-calibrator` moves its own touch target around.

No, for calibration to work the points cannot be the same (nor in a straight line)

**Comment by andreabolognani** [comment]
That would probably explain why the data I'm getting back is garbage :)
